#!/bin/bash
#SBATCH --job-name=rellstab_Ahal_v2-Aha09-trim
#SBATCH --time=02:59:00
#SBATCH --mem=5000M
#SBATCH --cpus-per-task=16
#SBATCH --output=rellstab_Ahal_v2-Aha09-trim_%j.out
#SBATCH --mail-user=james.whiting@ucalgary.ca
#SBATCH --mail-type=ALL

source /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/bash_variables

module load nixpkgs/16.09 gcc/7.3.0 fastp/0.19.5

fastp -i /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/SRR964271_R1.fastq.gz -o /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/01_trimmed/SRR964271_R1_trimmed.fastq.gz -I /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/SRR964271_R2.fastq.gz -O /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/01_trimmed/SRR964271_R2_trimmed.fastq.gz -g --cut_window_size 5 --cut_mean_quality 30 --n_base_limit 20 --length_required 75 -h /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/01_trimmed/SRR964271__trimmed_R1_R2_stats.html --cut_by_quality3 --thread 16 --json /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/01_trimmed/SRR964271__trimmed_R1_R2.json  > /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/01_trimmed/SRR964271__trimmed_R1_R2_stats.log

# cut_window_size=5 - the size of the sliding window for sliding window trimming, default is 4 (int [=4])
# --cut_mean_quality=30 - the bases in the sliding window with mean quality below cutting_quality will be cut, default is Q20 (int [=20])
# --n_base_limit - if one read's number of N base is >n_base_limit, then this read/pair is discarded. Default is 5 (int [=5])
# --length_required - reads shorter than length_required will be discarded, default is 15. (int [=15])

# once finished, map using bwa mem
    source /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/bash_variables
python $HOME/pipeline/02_bwa-map_view_sort_index_flagstat.py /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir Aha09
