#!/bin/bash
#SBATCH --time=23:59:00
#SBATCH --mem=55000M
#SBATCH --nodes=1
#SBATCH --ntasks=32
#SBATCH --cpus-per-task=1
#SBATCH --job-name=rellstab_Ahal_v2-Aha09-bwa
#SBATCH --output=rellstab_Ahal_v2-Aha09-bwa_%j.out
#SBATCH --mail-user=james.whiting@ucalgary.ca
#SBATCH --mail-type=ALL

# get RGID and RGPU
RGID=$(zcat /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/01_trimmed/SRR964271_R1_trimmed.fastq.gz | head -n1 | sed 's/:/_/g' | cut -d "_" -f1,2,3,4)
RGPU=$RGID.SRX342616

# map, sam to bam, sort by coordinate, index
module load bwa/0.7.17
bwa mem -t 32 -M -R "@RG\tID:$RGID\tSM:Aha09\tPL:ILLUMINA\tLB:SRX342616\tPU:$RGPU" /home/jimw91/scratch/pool_snpcalling/rellstab_Aalp/03_genome/GCA_900078215.1_Ahal2.2_genomic.fasta /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/01_trimmed/SRR964271_R1_trimmed.fastq.gz /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/01_trimmed/SRR964271_R2_trimmed.fastq.gz > /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/02a_samfiles/SRR964271_R1R2_trimmed.sam
module unload bwa

# -t 32 - threads
# -M - mark shorter split hits as secondary
# -R - read group header line such as '@RG\tID:foo\tSM:bar' [null]

module load nixpkgs/16.09  gcc/7.3.0 samtools/1.9
samtools view -@ 32 -q 20 -F 0x0004 -f 0x0002 -Sb /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/02a_samfiles/SRR964271_R1R2_trimmed.sam > /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/02b_bamfiles/SRR964271_R1R2_trimmed.bam
samtools sort -@ 32 /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/02b_bamfiles/SRR964271_R1R2_trimmed.bam > /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/02c_sorted_bamfiles/SRR964271_R1R2_trimmed_sorted.bam
samtools index /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/02c_sorted_bamfiles/SRR964271_R1R2_trimmed_sorted.bam
samtools flagstat /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/02c_sorted_bamfiles/SRR964271_R1R2_trimmed_sorted.bam > /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/02c_sorted_bamfiles/SRR964271_R1R2_trimmed_sorted.bam.flagstats
module unload samtools

# -@ - threads
# -q - only include reads with mapping quality >= Int [0]
# -f INT only include reads with all  of the FLAGs in INT present [0]
# -F INT only include reads with none of the FLAGS in INT present [0]
# -S - ignored (input format is auto-detected)
# -b - output BAM

module load nixpkgs/16.09 gcc/7.3.0 bedtools/2.27.1
bedtools bamtobed -i /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/02c_sorted_bamfiles/SRR964271_R1R2_trimmed_sorted.bam > /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/02c_sorted_bamfiles/SRR964271_R1R2_trimmed_sortedbam.coord
module unload bedtools



# mark and build
source /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/bash_variables
python $HOME/pipeline/03_mark_build.py /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2 Aha09
