#!/bin/bash
#SBATCH --time=11:59:00
#SBATCH --mem=30000M
#SBATCH --ntasks=1
#SBATCH --job-name=rellstab_Ahal_v2-Aha09-mark
#SBATCH --output=rellstab_Ahal_v2-Aha09-mark_%j.out
#SBATCH --mail-user=james.whiting@ucalgary.ca
#SBATCH --mail-type=ALL

# remove dups
module load java
module load nixpkgs/16.09 picard/2.18.9
export _JAVA_OPTIONS="-Xms256m -Xmx27g"
java -Djava.io.tmpdir=$SLURM_TMPDIR -jar $EBROOTPICARD/picard.jar MarkDuplicates I=/home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/02c_sorted_bamfiles/SRR964271_R1R2_trimmed_sorted.bam O=/home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/03_dedup_rg_filtered_indexed_sorted_bamfiles/Aha09_rd.bam MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 M=/home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/03_dedup_rg_filtered_indexed_sorted_bamfiles/Aha09_rd_dupstat.txt REMOVE_DUPLICATES=true

# Build bam index for GATK
java -jar $EBROOTPICARD/picard.jar BuildBamIndex I=/home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/03_dedup_rg_filtered_indexed_sorted_bamfiles/Aha09_rd.bam
module unload picard

# get more dup stats
module load nixpkgs/16.09  gcc/7.3.0 samtools/1.9
samtools flagstat /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/03_dedup_rg_filtered_indexed_sorted_bamfiles/Aha09_rd.bam > /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/03_dedup_rg_filtered_indexed_sorted_bamfiles/Aha09_rd.bam.flagstats
module unload samtools

# call next step
source /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/bash_variables

python $HOME/pipeline/04_realignTargetCreator.py /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2 Aha09 /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/03_dedup_rg_filtered_indexed_sorted_bamfiles/Aha09_rd.bam
