#!/bin/bash
#SBATCH --time=7-00:00:00
#SBATCH --mem=30000M
#SBATCH --nodes=1
#SBATCH --ntasks=32
#SBATCH --cpus-per-task=1
#SBATCH --job-name=rellstab_Ahal_v2-Aha09-realign
#SBATCH --output=rellstab_Ahal_v2-Aha09-realign_%j.out
#SBATCH --mail-user=james.whiting@ucalgary.ca
#SBATCH --mail-type=ALL

# realign using the GATK
module load java
module load nixpkgs/16.09 gatk/3.8
export _JAVA_OPTIONS="-Xms256m -Xmx28g"
java -Djava.io.tmpdir=$SLURM_TMPDIR -jar $EBROOTGATK/GenomeAnalysisTK.jar -T RealignerTargetCreator -R /home/jimw91/scratch/pool_snpcalling/rellstab_Aalp/03_genome/GCA_900078215.1_Ahal2.2_genomic.fasta --num_threads 32 -I /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/03_dedup_rg_filtered_indexed_sorted_bamfiles/Aha09_rd.bam -o /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/04_realign/Aha09_realingment_targets.list
module unload gatk

# next step
source /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/bash_variables
python $HOME/pipeline/05_indelRealign.py /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2 Aha09 /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/03_dedup_rg_filtered_indexed_sorted_bamfiles/Aha09_rd.bam /home/jimw91/scratch/pool_snpcalling/rellstab_Aalp/03_genome/GCA_900078215.1_Ahal2.2_genomic.fasta
