#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --job-name=rellstab_Ahal_v2-varscan_bedfile_0000
#SBATCH --time='7-00:00:00'
#SBATCH --mem=2000M
#SBATCH --output=rellstab_Ahal_v2-varscan_bedfile_0000_%j.out

# run VarScan (v.2.4.2)
module load java
module load nixpkgs/16.09 gcc/7.3.0 samtools/1.9
samtools view -b -L /home/jimw91/scratch/pool_snpcalling/rellstab_Aalp/03_genome/bedfiles_GCA_900078215.1_Ahal2.2_genomic/GCA_900078215.1_Ahal2.2_genomic_bedfile_0000.bed /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/04_realign/AhaN4_realigned_reads.bam > $SLURM_TMPDIR/AhaN4_realigned_0000.bam
samtools view -b -L /home/jimw91/scratch/pool_snpcalling/rellstab_Aalp/03_genome/bedfiles_GCA_900078215.1_Ahal2.2_genomic/GCA_900078215.1_Ahal2.2_genomic_bedfile_0000.bed /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/04_realign/AhaN3_realigned_reads.bam > $SLURM_TMPDIR/AhaN3_realigned_0000.bam
samtools view -b -L /home/jimw91/scratch/pool_snpcalling/rellstab_Aalp/03_genome/bedfiles_GCA_900078215.1_Ahal2.2_genomic/GCA_900078215.1_Ahal2.2_genomic_bedfile_0000.bed /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/04_realign/AhaN1_realigned_reads.bam > $SLURM_TMPDIR/AhaN1_realigned_0000.bam
samtools view -b -L /home/jimw91/scratch/pool_snpcalling/rellstab_Aalp/03_genome/bedfiles_GCA_900078215.1_Ahal2.2_genomic/GCA_900078215.1_Ahal2.2_genomic_bedfile_0000.bed /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/04_realign/Aha18_realigned_reads.bam > $SLURM_TMPDIR/Aha18_realigned_0000.bam
samtools view -b -L /home/jimw91/scratch/pool_snpcalling/rellstab_Aalp/03_genome/bedfiles_GCA_900078215.1_Ahal2.2_genomic/GCA_900078215.1_Ahal2.2_genomic_bedfile_0000.bed /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/04_realign/Aha31_realigned_reads.bam > $SLURM_TMPDIR/Aha31_realigned_0000.bam
samtools view -b -L /home/jimw91/scratch/pool_snpcalling/rellstab_Aalp/03_genome/bedfiles_GCA_900078215.1_Ahal2.2_genomic/GCA_900078215.1_Ahal2.2_genomic_bedfile_0000.bed /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/04_realign/Aha21_realigned_reads.bam > $SLURM_TMPDIR/Aha21_realigned_0000.bam
samtools view -b -L /home/jimw91/scratch/pool_snpcalling/rellstab_Aalp/03_genome/bedfiles_GCA_900078215.1_Ahal2.2_genomic/GCA_900078215.1_Ahal2.2_genomic_bedfile_0000.bed /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/04_realign/Aha09_realigned_reads.bam > $SLURM_TMPDIR/Aha09_realigned_0000.bam
samtools view -b -L /home/jimw91/scratch/pool_snpcalling/rellstab_Aalp/03_genome/bedfiles_GCA_900078215.1_Ahal2.2_genomic/GCA_900078215.1_Ahal2.2_genomic_bedfile_0000.bed /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/04_realign/Aha19_realigned_reads.bam > $SLURM_TMPDIR/Aha19_realigned_0000.bam
samtools view -b -L /home/jimw91/scratch/pool_snpcalling/rellstab_Aalp/03_genome/bedfiles_GCA_900078215.1_Ahal2.2_genomic/GCA_900078215.1_Ahal2.2_genomic_bedfile_0000.bed /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/04_realign/Aha11_realigned_reads.bam > $SLURM_TMPDIR/Aha11_realigned_0000.bam
samtools mpileup -B -f /home/jimw91/scratch/pool_snpcalling/rellstab_Aalp/03_genome/GCA_900078215.1_Ahal2.2_genomic.fasta $SLURM_TMPDIR/AhaN4_realigned_0000.bam $SLURM_TMPDIR/AhaN3_realigned_0000.bam $SLURM_TMPDIR/AhaN1_realigned_0000.bam $SLURM_TMPDIR/Aha18_realigned_0000.bam $SLURM_TMPDIR/Aha31_realigned_0000.bam $SLURM_TMPDIR/Aha21_realigned_0000.bam $SLURM_TMPDIR/Aha09_realigned_0000.bam $SLURM_TMPDIR/Aha19_realigned_0000.bam $SLURM_TMPDIR/Aha11_realigned_0000.bam | java -Xmx15g -jar $VARSCAN_DIR/VarScan.v2.4.3.jar mpileup2cns --min-coverage 8 --p-value 0.05 --min-var-freq 0.002777777777777778 --strand-filter 1 --min-freq-for-hom 0.80 --min-avg-qual 20 --output-vcf 1 > /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/varscan/rellstab_Ahal_v2_varscan_bedfile_0000.vcf

# Remove ambiguity
awk '$1 ~ /^#/ {print $0;next} {if ($4 ~ /A|C|T|G|\./ && $5 ~ /A|C|T|G|\./) print $0}' /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/varscan/rellstab_Ahal_v2_varscan_bedfile_0000.vcf > /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/varscan/rellstab_Ahal_v2_varscan_bedfile_0000.vcf.tmp && mv /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/varscan/rellstab_Ahal_v2_varscan_bedfile_0000.vcf.tmp /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/varscan/rellstab_Ahal_v2_varscan_bedfile_0000.vcf

module unload samtools


# vcf -> table (multiallelic to multiple lines, filtered in combine_varscan.py
module load nixpkgs/16.09 gatk/4.1.0.0
gatk VariantsToTable --variant /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/varscan/rellstab_Ahal_v2_varscan_bedfile_0000.vcf -F CHROM -F POS -F REF -F ALT -F AF -F QUAL -F TYPE -F FILTER -F ADP -F WT -F HET -F HOM -F NC -GF GT -GF GQ -GF SDP -GF DP -GF FREQ -GF PVAL -GF AD -GF RD -O /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/varscan/rellstab_Ahal_v2_varscan_bedfile_0000_table.txt --split-multi-allelic
module unload gatk

# gzip outfiles to save space
module load nixpkgs/16.09  gcc/7.3.0 htslib/1.9
cd $(dirname /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/varscan/rellstab_Ahal_v2_varscan_bedfile_0000.vcf)
bgzip -f /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/rellstab_Ahal_v2/varscan/rellstab_Ahal_v2_varscan_bedfile_0000.vcf

# if any other varscan jobs are hanging due to priority, change the account
source /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir/bash_variables
python $HOME/pipeline/balance_queue.py varscan /home/jimw91/scratch/pool_snpcalling/rellstab_Ahal/parentdir
